export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE';
export const GET_CATEGORIES_PENDING = 'GET_CATEGORIES_PENDING';
export const GET_CATEGORY_IMAGES_SUCCESS = 'GET_CATEGORY_IMAGES_SUCCESS';
export const GET_CATEGORY_IMAGES_FAILURE = 'GET_CATEGORY_IMAGES_FAILURE';
export const GET_CATEGORY_IMAGES_PENDING = 'GET_CATEGORY_IMAGES_PENDING';
